---
name: Update PRs

on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  update:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    steps:
      - name: Update Pull Requests
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const opts = github.rest.pulls.list.endpoint.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              base: context.ref.replace('refs/heads/', ''),
            })
            const prs = await github.paginate(opts)
            for (const pr of prs) {
              core.debug(JSON.stringify(pr))
              core.info(`Updating PR #${pr.number}`)
              github.rest.pulls.updateBranch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
              }).then(function(result) {
                core.debug(JSON.stringify(result))
                core.info(JSON.stringify(result.data))
              }).catch(function(error) {
                core.error(error)
              })
            }
